#!/bin/bash
K=$1
L=$2
DENSITY=$3
N=$4
T=$5
abund=$6
threshold=$7
distance=2
C=$8
TH=$9
echo "Running reference..."
cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- dmel_chr4.fa -k $K -l $L -n $N -t 1 --density $DENSITY --minabund 1 --threads $TH --levenshtein-minimizers 0 --prefix dmel_chr4 --reference --no-error-correct #--counts reads-0.05.ascii.txt 
start=`date +%s`
echo "Running reads..."

cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- reads-0.05.fa -k $K -l $L -n $N -t $T --threads $TH --density $DENSITY --minabund $abund --correction-threshold $threshold --distance $distance --levenshtein-minimizers 0 --prefix dmel_chr4_reads-0.05  #--counts reads-0.05.ascii.txt
#cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- reads-0.00.fa -k $K -l $L -n $N -t $T --density $DENSITY --minabund $abund --no-error-correct --prefix dmel_chr4_reads-0.05

end=`date +%s`
echo "Running evaluation..."
pypy3 utils/evaluate_ec.py  dmel_chr4.ec_data  dmel_chr4_reads-0.05.ec_data  dmel_chr4_reads-0.05.postcor.ec_data dmel_chr4_reads-0.05.poa.ec_data | tee ec.txt
echo "Comparing k-mers..."
python utils/compare_kmers.py dmel_chr4.sequences dmel_chr4_reads-0.05.sequences
runtime=$((end-start))
echo "Runtime was $runtime seconds."
utils/simplify dmel_chr4_reads-0.05


