#!/bin/bash
K=$1
L=$2
DENSITY=$3
N=$4
T=$5
abund=$6
threshold=$7
distance=2
C=$8
TH=$9
cp ../dsk/build/bin/* .
./dsk -file /scratch2/ekim/rust-mhdbg/reads-0.05.fa -kmer-size $L
./dsk2ascii -file reads-0.05.h5 -out dmel_chr4.ascii.txt
echo "Running reference..."
cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- dmel_chr4.fa -k $K -l $L -n $N -t 1 -c $C --counts dmel_chr4.ascii.txt --density $DENSITY --minabund 1 --threads $TH --levenshtein-minimizers 0 --prefix dmel_chr4 --reference --no-error-correct #--counts reads-0.05.ascii.txt 
start=`date +%s`
echo "Running reads..."

cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- reads-0.05.fa -k $K -l $L -n $N -t $T -c $C --threads $TH --density $DENSITY --counts dmel_chr4.ascii.txt --minabund $abund --correction-threshold $threshold --distance $distance --levenshtein-minimizers 0 --prefix dmel_chr4_reads-0.05  #--counts reads-0.05.ascii.txt
#cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- reads-0.00.fa -k $K -l $L -n $N -t $T --density $DENSITY --minabund $abund --no-error-correct --prefix dmel_chr4_reads-0.05

end=`date +%s`
echo "Comparing k-mers..."
python utils/compare_kmers.py dmel_chr4.sequences dmel_chr4_reads-0.05.sequences
runtime=$((end-start))
echo "Runtime was $runtime seconds."
utils/simplify dmel_chr4_reads-0.05


