#!/bin/bash
K=$1
L=$2
DENSITY=$3
N=$4
T=$5
abund=$6
threshold=$7
distance=$8
touch bench/canu-bench-hifi-$1$2.txt
echo "Running reference..."
cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- /scratch2/dmel_ref.fa -k $K -l $L -n $N -t 1 --density $DENSITY --minabund 1 --levenshtein-minimizers 0 --prefix canu_hifi_ref --reference --no-error-correct 
start=`date +%s`
echo "Running reads..."
command time -v cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- /scratch2/canu_hifi.fa -k $K -l $L -n $N -t $T --density $DENSITY --minabund 2 --correction-threshold $threshold --distance $distance --no-error-correct --prefix canu_hifi 2>&1 | tee -a bench/canu-bench-hifi-$1$2.txt
end=`date +%s`
echo "Running evaluation..."
pypy3 ~/rust-mhdbg/utils/evaluate_ec.py  canu_hifi_ref.ec_data  canu_hifi.ec_data  canu_hifi.postcor.ec_data canu_hifi.poa.ec_data | tee ec.txt
echo "Comparing k-mers..."
python utils/compare_kmers.py canu_hifi_ref.sequences canu_hifi.sequences dmel_ref.fa
runtime=$((end-start))
echo "Runtime was $runtime seconds."
