#!/bin/bash
K=$1
L=$2
DENSITY=$3
N=$4
T=$5
abund=$6
threshold=$7
distance=$8
C=$9
touch bench/canu-bench-hifi-$1$2.txt
cp ../dsk/build/bin/* .
./dsk -file /scratch2/ekim/canu_hifi_hpc.fa -kmer-size $L
./dsk2ascii -file canu_hifi_hpc.h5 -out canu_hifi_hpc.ascii.txt
echo "Running reference..."
cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- /scratch2/ekim/dmel_ref_hpc.fa -k $K -l $L -n $N -t 1 -c $C --density $DENSITY --minabund 1 --levenshtein-minimizers 0 --prefix canu_hifi_ref --reference --no-error-correct --counts canu_hifi_hpc.ascii.txt
start=`date +%s`
echo "Running reads..."

command time -v cargo run --manifest-path ../rust-mhdbg/Cargo.toml --release -- /scratch2/ekim/canu_hifi_hpc.fa -k $K -l $L -n $N -t $T -c $C --density $DENSITY --minabund 2 --correction-threshold $threshold --counts canu_hifi_hpc.ascii.txt --distance $distance --no-error-correct --prefix canu_hifi 2>&1 | tee -a bench/canu-bench-hifi-$1$2.txt
end=`date +%s`
echo "Comparing k-mers..."
python utils/compare_kmers.py canu_hifi_ref.sequences canu_hifi.sequences
runtime=$((end-start))
echo "Runtime was $runtime seconds."
