#!/bin/bash
set -x
if [[ $# -eq 0 ]] ; then
    #echo 'running main.py'
    #python main.py
    base="graph"
else
    base="$1"
fi
gfaview $base.gfa -u > $base.unitigs.gfa
gfaview $base.gfa -t -u > $base.notips.gfa
gfaview $base.gfa -b -u > $base.notips.nobubbles.gfa
gfaview $base.notips.nobubbles.gfa -t -b -u > $base.notips.nobubbles.again.gfa
echo ~/tools/Bandage/Bandage load $base.notips.nobubbles.again.gfa 

python utils/retrace_minimizers.py $base.sequences $base.notips.gfa
python utils/retrace_minimizers.py $base.sequences $base.notips.nobubbles.gfa
python utils/retrace_minimizers.py $base.notips.nobubbles.sequences $base.notips.nobubbles.again.gfa

python utils/output_basic_sequences.py  $base.sequences $base.notips.nobubbles.again.sequences
python utils/sequences_file_to_fasta.py  $base.notips.nobubbles.again.sequences $base.notips.nobubbles.again.fasta
