#!/bin/bash
if [[ $# -eq 0 ]] ; then
    #echo 'running main.py'
    #python main.py
    base="graph"
else
    base="$1"
fi
gfaview $base.gfa -u > $base.unitigs.gfa
gfaview $base.gfa -t -u > $base.notips.gfa
gfaview $base.gfa -b -u > $base.notips.nobubbles.gfa
gfaview $base.notips.nobubbles.gfa -t -b -u > $base.notips.nobubbles.again.gfa
echo ~/tools/Bandage/Bandage load $base.notips.nobubbles.again.gfa 
